# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='math.proto',
  package='math',
  syntax='proto3',
  serialized_pb=_b('\n\nmath.proto\x12\x04math\"5\n\x0bMathRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\t\n\x01\x62\x18\x03 \x01(\x05\"\x1b\n\tMathReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32<\n\nCalculator\x12.\n\x06\x44oMath\x12\x11.math.MathRequest\x1a\x0f.math.MathReply\"\x00\x42*\n\x15io.grpc.examples.mathB\tMathProtoP\x01\xa2\x02\x03MTHb\x06proto3')
)




_MATHREQUEST = _descriptor.Descriptor(
  name='MathRequest',
  full_name='math.MathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='math.MathRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='math.MathRequest.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='math.MathRequest.b', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=73,
)


_MATHREPLY = _descriptor.Descriptor(
  name='MathReply',
  full_name='math.MathReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='math.MathReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['MathRequest'] = _MATHREQUEST
DESCRIPTOR.message_types_by_name['MathReply'] = _MATHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MathRequest = _reflection.GeneratedProtocolMessageType('MathRequest', (_message.Message,), dict(
  DESCRIPTOR = _MATHREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:math.MathRequest)
  ))
_sym_db.RegisterMessage(MathRequest)

MathReply = _reflection.GeneratedProtocolMessageType('MathReply', (_message.Message,), dict(
  DESCRIPTOR = _MATHREPLY,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:math.MathReply)
  ))
_sym_db.RegisterMessage(MathReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025io.grpc.examples.mathB\tMathProtoP\001\242\002\003MTH'))

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='math.Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=104,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoMath',
    full_name='math.Calculator.DoMath',
    index=0,
    containing_service=None,
    input_type=_MATHREQUEST,
    output_type=_MATHREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
